import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Users, Plus, Search, Lock, Globe, School } from 'lucide-react';
import { Pod, PodMember } from '@/api/entities';
import { useApi } from '@/components/hooks/useApi';
import { LoadingSpinner, EmptyState } from '@/components/shared/LoadingStates';
import { useToast } from '@/components/ui/use-toast';
import { motion } from 'framer-motion';

const PodCard = ({ pod, currentUser, onJoin, isJoining }) => {
  const getTypeIcon = () => {
    switch (pod.type || 'public') {
      case 'private': return <Lock className="w-4 h-4" />;
      case 'school': return <School className="w-4 h-4" />;
      default: return <Globe className="w-4 h-4" />;
    }
  };

  const getTypeLabel = () => {
    switch (pod.type || 'public') {
      case 'private': return 'Private';
      case 'school': return 'School';
      default: return 'Public';
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.95 }}
      animate={{ opacity: 1, scale: 1 }}
      whileHover={{ y: -2 }}
      className="h-full"
    >
      <Card className="h-full hover:shadow-lg transition-shadow cursor-pointer">
        <CardHeader className="pb-3">
          <div className="flex items-center justify-between">
            <CardTitle className="text-lg">{pod.name}</CardTitle>
            <Badge variant="outline" className="flex items-center gap-1">
              {getTypeIcon()}
              {getTypeLabel()}
            </Badge>
          </div>
          {pod.description && (
            <p className="text-sm text-gray-600 line-clamp-2">{pod.description}</p>
          )}
        </CardHeader>

        <CardContent className="pt-0">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-2 text-sm text-gray-500">
              <Users className="w-4 h-4" />
              {pod.member_count || 0} members
            </div>
            {pod.is_autogenerated && (
              <Badge variant="secondary" className="text-xs">
                AI Suggested
              </Badge>
            )}
          </div>

          {pod.tags && pod.tags.length > 0 && (
            <div className="flex flex-wrap gap-1 mb-4">
              {pod.tags.slice(0, 3).map((tag, index) => (
                <Badge key={index} variant="outline" className="text-xs">
                  {tag}
                </Badge>
              ))}
              {pod.tags.length > 3 && (
                <Badge variant="outline" className="text-xs">
                  +{pod.tags.length - 3}
                </Badge>
              )}
            </div>
          )}

          <Button
            onClick={() => onJoin(pod)}
            disabled={isJoining}
            className="w-full bg-blue-600 hover:bg-blue-700"
            size="sm"
          >
            {pod.user_is_member ? 'View Pod' : 'Join Pod'}
          </Button>
        </CardContent>
      </Card>
    </motion.div>
  );
};

export default function CommunityPods({ user }) {
  const [pods, setPods] = useState([]);
  const [searchQuery, setSearchQuery] = useState('');
  const [isLoading, setIsLoading] = useState(true);
  const [joiningPod, setJoiningPod] = useState(null);
  const [activeTab, setActiveTab] = useState('discover');

  const api = useApi({ context: 'community-pods' });
  const { toast } = useToast();

  useEffect(() => {
    loadPods();
  }, []);

  const loadPods = async () => {
    setIsLoading(true);
    try {
      const podsData = await api.execute(() => Pod.list('-created_date'), {
        key: 'pods',
        errorContext: 'loading community pods'
      });
      
      setPods(podsData || []);
    } catch (error) {
      console.error('Failed to load pods:', error);
      toast({
        variant: "destructive",
        title: "Loading Error",
        description: "Failed to load community pods. Please try again."
      });
    } finally {
      setIsLoading(false);
    }
  };

  const handleJoinPod = async (pod) => {
    if (joiningPod) return;
    
    setJoiningPod(pod.id);
    try {
      if (pod.user_is_member) {
        // Navigate to pod view (would be implemented)
        toast({
          title: "Opening Pod",
          description: `Taking you to ${pod.name}...`
        });
      } else {
        // Join the pod
        await PodMember.create({
          pod_id: pod.id,
          user_id: user.id
        });

        toast({
          title: "Joined Pod!",
          description: `Welcome to ${pod.name}! You can now participate in discussions.`
        });

        // Reload pods to update membership status
        await loadPods();
      }
    } catch (error) {
      console.error('Pod join error:', error);
      toast({
        variant: "destructive",
        title: "Join Error",
        description: "Failed to join the pod. Please try again."
      });
    } finally {
      setJoiningPod(null);
    }
  };

  const filteredPods = pods.filter(pod =>
    pod.name?.toLowerCase().includes(searchQuery.toLowerCase()) ||
    pod.description?.toLowerCase().includes(searchQuery.toLowerCase()) ||
    pod.tags?.some(tag => tag.toLowerCase().includes(searchQuery.toLowerCase()))
  );

  const myPods = filteredPods.filter(pod => pod.user_is_member);
  const availablePods = filteredPods.filter(pod => !pod.user_is_member);

  return (
    <div className="p-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row gap-4 items-center justify-between mb-6">
        <div className="flex items-center gap-2 flex-1 max-w-md">
          <Search className="w-4 h-4 text-gray-400" />
          <Input
            placeholder="Search pods..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="border-0 bg-gray-50"
          />
        </div>
        
        <Button className="bg-blue-600 hover:bg-blue-700">
          <Plus className="w-4 h-4 mr-2" />
          Create Pod
        </Button>
      </div>

      {/* Tab Navigation */}
      <div className="flex gap-1 mb-6 bg-gray-100 p-1 rounded-lg w-fit">
        <Button
          variant={activeTab === 'discover' ? 'default' : 'ghost'}
          size="sm"
          onClick={() => setActiveTab('discover')}
          className="rounded-md"
        >
          Discover ({availablePods.length})
        </Button>
        <Button
          variant={activeTab === 'my-pods' ? 'default' : 'ghost'}
          size="sm"
          onClick={() => setActiveTab('my-pods')}
          className="rounded-md"
        >
          My Pods ({myPods.length})
        </Button>
      </div>

      {/* Content */}
      {isLoading ? (
        <div className="flex justify-center py-12">
          <LoadingSpinner text="Loading pods..." />
        </div>
      ) : (
        <>
          {activeTab === 'discover' && (
            <>
              {availablePods.length === 0 ? (
                <EmptyState
                  title="No pods found"
                  description={searchQuery ? "Try adjusting your search terms." : "Be the first to create a pod for your community!"}
                  action={
                    <Button className="bg-blue-600 hover:bg-blue-700">
                      <Plus className="w-4 h-4 mr-2" />
                      Create First Pod
                    </Button>
                  }
                />
              ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                  {availablePods.map(pod => (
                    <PodCard
                      key={pod.id}
                      pod={pod}
                      currentUser={user}
                      onJoin={handleJoinPod}
                      isJoining={joiningPod === pod.id}
                    />
                  ))}
                </div>
              )}
            </>
          )}

          {activeTab === 'my-pods' && (
            <>
              {myPods.length === 0 ? (
                <EmptyState
                  title="No pods joined yet"
                  description="Join some pods to connect with other parents and participate in discussions."
                  action={
                    <Button onClick={() => setActiveTab('discover')}>
                      <Users className="w-4 h-4 mr-2" />
                      Discover Pods
                    </Button>
                  }
                />
              ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                  {myPods.map(pod => (
                    <PodCard
                      key={pod.id}
                      pod={pod}
                      currentUser={user}
                      onJoin={handleJoinPod}
                      isJoining={joiningPod === pod.id}
                    />
                  ))}
                </div>
              )}
            </>
          )}
        </>
      )}
    </div>
  );
}