/* eslint-env node */

export const GAP_STATUSES = Object.freeze(['open', 'scaffolded', 'blocked', 'ready_for_validation']);

export const GAP_BACKLOG = Object.freeze([
  {
    id: 'GAP-001',
    title: 'Route-by-route server-side enforcement',
    status: 'open',
    priority: 'P0',
    owner: 'platform-security',
    regulatoryImpact: ['COPPA', 'FERPA', 'state_student_privacy'],
    affectedSystems: ['Express routes', 'Nhost functions', 'GraphQL operations', 'admin APIs'],
    currentState: 'Central policy helpers exist, but every sensitive route/function still needs explicit integration proof.',
    risk: 'A UI-hidden or direct API path could bypass relationship, consent, role, or tenant checks.',
    recommendation: 'Create a route/function inventory and require each sensitive handler to declare its data classification and policy middleware.',
    solution: 'Add a policy manifest for protected handlers, wire helpers into high-risk routes first, and fail CI when a sensitive route lacks enforcement metadata.',
    implementationSteps: [
      'Inventory Express routers, Nhost functions, and GraphQL operations that touch classified entities.',
      'Add per-handler metadata: entity, action, required role/scope, tenant source, relationship/consent requirement, audit event.',
      'Wrap handlers with shared `requireStudentScope`, `requireConsent`, and `auditEvent` calls.',
      'Add direct API bypass tests for guardian, teacher, school admin, and district admin roles.',
    ],
    acceptanceCriteria: [
      'Every sensitive server handler has classification and enforcement metadata.',
      'Direct API calls fail closed without verified relationship/tenant/scope/consent.',
      'Critical denied access paths emit PII-minimized audit events.',
    ],
    evidence: ['policy manifest coverage report', 'direct bypass Jest/Supertest results', 'audit event assertions'],
    dependencies: ['P0 helpers', 'route inventory'],
  },
  {
    id: 'GAP-002',
    title: 'Hasura and GraphQL permission proof',
    status: 'open',
    priority: 'P0',
    owner: 'data-platform',
    regulatoryImpact: ['FERPA', 'COPPA', 'state_student_privacy'],
    affectedSystems: ['Hasura metadata', 'Nhost permissions', 'GraphQL client operations'],
    currentState: 'Readiness scripts and metadata exist; live row/column permission evidence remains manual.',
    risk: 'GraphQL row filters or column permissions can drift from Express policy and leak cross-tenant records.',
    recommendation: 'Treat Hasura metadata as the data-plane source of truth and generate role-based permission evidence.',
    solution: 'Add permission smoke fixtures for parent, teacher, school_admin, district_admin, and anonymous roles against sensitive tables.',
    implementationSteps: [
      'Map classified entities to Hasura table metadata files.',
      'Add role fixtures with tenant, school, class, and guardian relationship claims.',
      'Run negative GraphQL queries for cross-tenant and unverified relationship access.',
      'Archive smoke output in compliance reports.',
    ],
    acceptanceCriteria: [
      'Sensitive GraphQL operations deny unauthorized roles and cross-tenant claims.',
      'Column-level access excludes unnecessary PII where possible.',
      'CI blocks metadata changes that remove protected permissions.',
    ],
    evidence: ['Hasura permission smoke artifact', 'metadata diff review', 'negative GraphQL query logs'],
    dependencies: ['local/staging Hasura endpoint', 'seeded permission fixtures'],
  },
  {
    id: 'GAP-003',
    title: 'Consent ledger API and privacy preference center',
    status: 'scaffolded',
    priority: 'P0',
    owner: 'privacy-product',
    regulatoryImpact: ['COPPA', 'PPRA', 'FERPA'],
    affectedSystems: ['privacy UI', 'backend APIs', 'consent_ledger table'],
    currentState: 'Ledger helpers and migration scaffold exist; durable API/UI flows are not wired.',
    risk: 'Product surfaces could collect/use child data without scoped, versioned, revocable consent.',
    recommendation: 'Ship privacy preferences before enabling messaging, AI, analytics, third-party integrations, surveys, or media/community display.',
    solution: 'Create tenant-scoped consent APIs and a parent/admin preference center backed by immutable consent history.',
    implementationSteps: [
      'Add `POST /api/privacy/consents`, `DELETE /api/privacy/consents/:scope`, and `GET /api/privacy/consents/history` routes.',
      'Render separate toggles for AI, messaging, weekly digest, optional analytics, integrations, media/community display, and surveys.',
      'Require current notice/consent versions before protected processing.',
      'Emit `consent.granted` and `consent.revoked` audit events.',
    ],
    acceptanceCriteria: [
      'Revocation blocks future scoped processing.',
      'Consent history preserves version, notice, source, and evidence reference.',
      'Missing consent blocks child-data use in AI, messaging, analytics, integrations, and PPRA prompts.',
    ],
    evidence: ['API tests', 'privacy center a11y tests', 'audit log assertions'],
    dependencies: ['migration applied', 'notice version registry'],
  },
  {
    id: 'GAP-004',
    title: 'Guardian relationship operations',
    status: 'scaffolded',
    priority: 'P0',
    owner: 'identity-product',
    regulatoryImpact: ['COPPA', 'FERPA'],
    affectedSystems: ['guardian dashboards', 'school admin approvals', 'exports/deletions', 'messaging'],
    currentState: 'Relationship states and access helpers exist; invitation, dispute, and revocation APIs are not wired.',
    risk: 'Parents/guardians may access student data before school verification or after revocation/dispute.',
    recommendation: 'Make relationship verification a prerequisite for every guardian-facing student-data route.',
    solution: 'Add relationship lifecycle APIs with school approval, guardian confirmation, revocation, dispute handling, and audit logs.',
    implementationSteps: [
      'Create relationship create/invite/verify/revoke/dispute endpoints.',
      'Add admin review UI for pending and disputed relationships.',
      'Apply relationship checks to guardian dashboard, student profile, messaging, exports, deletion, AI insights, assignments, and notifications.',
      'Add cache invalidation so revocation immediately removes access.',
    ],
    acceptanceCriteria: [
      'Unverified, revoked, disputed, and cross-tenant relationships fail closed.',
      'Verified relationships grant only appropriate student data.',
      'Every state change is auditable.',
    ],
    evidence: ['relationship API tests', 'guardian dashboard bypass tests', 'audit events'],
    dependencies: ['identity model mapping', 'school admin approval UI'],
  },
  {
    id: 'GAP-005',
    title: 'Operational DSAR/export/deletion rehearsal',
    status: 'scaffolded',
    priority: 'P0',
    owner: 'privacy-ops',
    regulatoryImpact: ['COPPA', 'FERPA', 'state_privacy'],
    affectedSystems: ['DSAR APIs', 'retention jobs', 'audit logs', 'admin console'],
    currentState: 'Lifecycle registry and helper scaffolds exist; rehearsal command and production storage workflow are incomplete.',
    risk: 'Support cannot prove access/export/deletion obligations under district contracts or privacy requests.',
    recommendation: 'Add a one-command rehearsal that creates an export, revokes consent, requests deletion, anonymizes, and preserves audit integrity.',
    solution: 'Implement a DSAR rehearsal script that runs against seeded data and writes a redacted evidence report.',
    implementationSteps: [
      'Seed a guardian, student, school, roster, message, assignment, AI interaction, consent history, and audit summary.',
      'Run authorized and unauthorized export/deletion requests.',
      'Verify legal hold and school retention blocks where expected.',
      'Write `/artifacts/ops/dsar-rehearsal.*` with redacted output.',
    ],
    acceptanceCriteria: [
      'Authorized export includes required data categories.',
      'Unauthorized export/deletion fails closed.',
      'Deletion preserves immutable audit integrity and redacts subject PII.',
    ],
    evidence: ['DSAR rehearsal report', 'Jest integration tests', 'retention policy report'],
    dependencies: ['seed data fixtures', 'admin route integration'],
  },
  {
    id: 'GAP-006',
    title: 'Admin privacy/compliance console',
    status: 'open',
    priority: 'P1',
    owner: 'admin-product',
    regulatoryImpact: ['FERPA', 'district_procurement', 'state_student_privacy'],
    affectedSystems: ['AdminCompliance', 'AdminAuditLogs', 'AdminAIGovernance', 'feature flag admin'],
    currentState: 'Admin pages exist; unified privacy/compliance console data sources are not fully connected.',
    risk: 'Schools/districts need engineering help to review consent, audit, lifecycle, incidents, AI review, and feature-gate status.',
    recommendation: 'Create a tenant-scoped compliance console that surfaces evidence without unnecessary raw PII.',
    solution: 'Add read-only compliance summary APIs and admin views for consent, relationships, roster imports, messaging health, audit logs, lifecycle requests, AI review, incidents, integrations, release gates, and accessibility evidence.',
    implementationSteps: [
      'Add `/api/admin/compliance/summary` with tenant-scoped aggregates.',
      'Add detail endpoints with pagination and redacted payloads.',
      'Audit admin access to student/family/school records.',
      'Add tests for cross-tenant admin denial and minimized payloads.',
    ],
    acceptanceCriteria: [
      'School admins see only their school; district admins see only their district.',
      'Console payloads redact or omit raw PII unless strictly necessary.',
      'Admin access emits audit events.',
    ],
    evidence: ['admin API tests', 'a11y smoke for console', 'redaction snapshot'],
    dependencies: ['consent/relationship/lifecycle tables', 'audit APIs'],
  },
  {
    id: 'GAP-007',
    title: 'AI governance route integration and review operations',
    status: 'scaffolded',
    priority: 'P0',
    owner: 'ai-platform',
    regulatoryImpact: ['COPPA', 'FERPA', 'PPRA', 'AI_governance'],
    affectedSystems: ['AI completion route', 'AI review queue', 'orchestrator', 'weekly briefs'],
    currentState: 'AI helpers and existing governance middleware exist; high-stakes review and consent need consistent integration across all AI paths.',
    risk: 'A non-completion AI path could log prompts, skip consent, or produce student-impacting recommendations without human review.',
    recommendation: 'Apply the same advisory-only, consent, redaction, retention, and review requirements to every AI prompt/output path.',
    solution: 'Route all AI prompt/output writes through `recordAITrace`-style policy handling or equivalent middleware.',
    implementationSteps: [
      'Inventory backend/orchestrator and Nhost weekly brief AI paths.',
      'Require AI consent and relationship scope when student data is present.',
      'Route high-stakes or PPRA-sensitive outputs to review queue.',
      'Block final-decision wording and model-training use without explicit authorization.',
    ],
    acceptanceCriteria: [
      'High-stakes AI is queued for review before student-impacting use.',
      'AI output is labeled advisory.',
      'Prompts/outputs are redacted in logs and traces.',
      'Missing AI consent blocks processing where required.',
    ],
    evidence: ['AI path inventory', 'AI review tests', 'redacted trace examples'],
    dependencies: ['review queue API', 'consent API'],
  },
  {
    id: 'GAP-008',
    title: 'Messaging and digest reliability with privacy suppression',
    status: 'scaffolded',
    priority: 'P1',
    owner: 'communications',
    regulatoryImpact: ['COPPA', 'FERPA', 'state_student_privacy'],
    affectedSystems: ['messages', 'notification queue', 'weekly briefs', 'digests'],
    currentState: 'Queue/retry helpers and existing notification tables exist; end-to-end privacy enforcement needs integration.',
    risk: 'Messages or digests could be sent after consent revocation, opt-out, relationship revocation, or tenant scope change.',
    recommendation: 'Centralize delivery authorization and suppression immediately before enqueue and send.',
    solution: 'Add a delivery service that checks tenant, role/relationship, consent, preferences, suppression list, and redacted templates.',
    implementationSteps: [
      'Integrate `assertMessagingAllowed` before message/digest enqueue.',
      'Add retry/backoff status transitions and dead-letter visibility.',
      'Redact delivery logs and notification templates.',
      'Audit sent/read/delete/suppressed events.',
    ],
    acceptanceCriteria: [
      'Revoked consent or opt-out suppresses delivery.',
      'Unauthorized cross-tenant messaging fails closed.',
      'Delivery failures are observable without raw message body logs.',
    ],
    evidence: ['delivery integration tests', 'redacted log fixtures', 'admin delivery health view'],
    dependencies: ['consent API', 'relationship API', 'notification preferences'],
  },
  {
    id: 'GAP-009',
    title: 'Roster import production workflow',
    status: 'scaffolded',
    priority: 'P1',
    owner: 'integrations',
    regulatoryImpact: ['FERPA', 'state_student_privacy'],
    affectedSystems: ['CSV import', 'OneRoster-lite', 'directory imports', 'SIS sync'],
    currentState: 'Preview helper detects deterministic keys, duplicates, and ambiguous rows; persistence/review/rollback workflow is incomplete.',
    risk: 'Roster collisions can create ghost users, duplicate identities, or cross-tenant student leakage.',
    recommendation: 'Ship roster import as a reviewed, auditable workflow before broader school integrations.',
    solution: 'Persist import previews, require admin approval for ambiguous rows, and support rollback references.',
    implementationSteps: [
      'Parse CSV/OneRoster-lite into normalized identity records.',
      'Detect duplicate students/guardians and cross-tenant collisions.',
      'Quarantine ambiguous rows for admin review.',
      'Audit import, update, error, approval, and rollback events.',
    ],
    acceptanceCriteria: [
      'Deterministic mappings prevent ghost users.',
      'Ambiguous records require review before activation.',
      'Cross-tenant collision fails closed.',
    ],
    evidence: ['roster import tests', 'review queue snapshots', 'audit events'],
    dependencies: ['directory import tables', 'school admin review UI'],
  },
  {
    id: 'GAP-010',
    title: 'Accessibility beyond smoke coverage',
    status: 'open',
    priority: 'P0',
    owner: 'design-system',
    regulatoryImpact: ['ADA_Title_II', 'WCAG', 'district_procurement'],
    affectedSystems: ['parent flows', 'teacher flows', 'admin flows', 'consent center', 'messaging', 'AI/chat'],
    currentState: 'Automated a11y smoke tests pass; full keyboard, focus, contrast, error, and screen-reader review remains incomplete.',
    risk: 'Core privacy/security actions may be inaccessible to parents, teachers, or admins.',
    recommendation: 'Add critical-path a11y tests for the flows that control access, consent, messaging, AI, and admin compliance.',
    solution: 'Create Playwright/aXe tests and manual evidence templates for consent, guardian approval, export/deletion, messaging, AI review, and admin console paths.',
    implementationSteps: [
      'Add keyboard-only tests for critical actions.',
      'Verify form labels, errors, modal/dialog semantics, and focus return.',
      'Add AI/chat transcript roles and announcement semantics.',
      'Document manual WCAG review evidence for procurement.',
    ],
    acceptanceCriteria: [
      'Critical forms have labels and accessible error messages.',
      'Modals/dialogs trap and restore focus correctly.',
      'AI/chat and notification controls are screen-reader friendly.',
    ],
    evidence: ['Playwright a11y tests', 'manual WCAG evidence', 'screen-reader notes'],
    dependencies: ['UI route availability', 'test credentials/fixtures'],
  },
  {
    id: 'GAP-011',
    title: 'Incident and breach response operations',
    status: 'scaffolded',
    priority: 'P1',
    owner: 'security-ops',
    regulatoryImpact: ['state_breach_laws', 'district_procurement'],
    affectedSystems: ['privacy incidents', 'audit logs', 'admin console', 'notice templates'],
    currentState: 'Incident model helper and migration scaffold exist; operational APIs, exports, and templates are not wired.',
    risk: 'Teachmo cannot reliably scope affected tenants/subjects/data classes or preserve evidence during an incident.',
    recommendation: 'Implement an incident workflow that scopes affected records by tenant/data class and avoids unnecessary PII.',
    solution: 'Add incident create/update APIs, affected-subject export, audit preservation, and non-legal notice template placeholders.',
    implementationSteps: [
      'Add tenant-scoped incident CRUD APIs.',
      'Add affected-user export helper with redaction.',
      'Preserve audit events for incident lifecycle transitions.',
      'Add school/parent/regulator notice placeholders with legal-review disclaimers.',
    ],
    acceptanceCriteria: [
      'Incidents can be created, triaged, contained, investigated, marked notify-required, and resolved.',
      'Affected records are scoped by tenant and data class.',
      'Incident data avoids unnecessary raw PII.',
    ],
    evidence: ['incident API tests', 'affected-subject export fixture', 'audit events'],
    dependencies: ['admin compliance console', 'tenant/data classification mapping'],
  },
  {
    id: 'GAP-012',
    title: 'Procurement and vendor evidence packet',
    status: 'open',
    priority: 'P1',
    owner: 'compliance-ops',
    regulatoryImpact: ['district_procurement', 'FERPA', 'state_student_privacy'],
    affectedSystems: ['docs', 'admin console', 'release artifacts', 'subprocessors/integrations'],
    currentState: 'Engineering evidence artifacts exist; DPA, subprocessors, no-sale/no-ad-targeting, and vendor review packet remain human-owned.',
    risk: 'District pilots may stall without operational proof and procurement-ready artifacts.',
    recommendation: 'Maintain a living evidence packet that links automated control results to human-reviewed legal/vendor artifacts.',
    solution: 'Add procurement checklist ownership, artifact locations, review cadence, and exception process.',
    implementationSteps: [
      'Create an evidence index for DPA, subprocessors, deletion/export, security scans, a11y, AI governance, incident response, and no-sale/no-targeting statements.',
      'Add owner and review cadence for each artifact.',
      'Block risky integrations until subprocessor review is complete.',
      'Document exceptions with owner, expiration, and compensating controls.',
    ],
    acceptanceCriteria: [
      'Every procurement artifact has an owner and current status.',
      'Subprocessor/integration enablement is audited and gated.',
      'No compliance claim is presented as a legal guarantee.',
    ],
    evidence: ['procurement evidence index', 'subprocessor review log', 'release report links'],
    dependencies: ['legal/vendor review', 'admin compliance console'],
  },
]);

export function getOpenGaps({ priority } = {}) {
  return GAP_BACKLOG.filter((gap) => gap.status !== 'ready_for_validation' && (!priority || gap.priority === priority));
}

export function getCriticalRemediationPlan() {
  return getOpenGaps({ priority: 'P0' }).map(({ id, title, owner, recommendation, implementationSteps, acceptanceCriteria }) => ({
    id,
    title,
    owner,
    recommendation,
    implementationSteps,
    acceptanceCriteria,
  }));
}

export function assertGapBacklogComplete(gaps = GAP_BACKLOG) {
  const missing = [];
  for (const gap of gaps) {
    for (const field of ['id', 'title', 'status', 'priority', 'owner', 'risk', 'recommendation', 'solution']) {
      if (!gap[field]) missing.push(`${gap.id || 'unknown'}:${field}`);
    }
    for (const field of ['regulatoryImpact', 'affectedSystems', 'implementationSteps', 'acceptanceCriteria', 'evidence']) {
      if (!Array.isArray(gap[field]) || gap[field].length === 0) missing.push(`${gap.id || 'unknown'}:${field}`);
    }
    if (!GAP_STATUSES.includes(gap.status)) missing.push(`${gap.id}:status`);
  }
  if (missing.length) throw new Error(`Incomplete remediation backlog: ${missing.join(', ')}`);
  return true;
}
