// Phase 1 route map (keep in sync with src/lib/orchestrator/types.ts)
export const ROUTES = {
  HUB_MESSAGE_SEND: 'HUB_MESSAGE_SEND',
  HUB_THREAD_SUMMARIZE: 'HUB_THREAD_SUMMARIZE',
  WEEKLY_BRIEF_GENERATE: 'WEEKLY_BRIEF_GENERATE',
  OFFICE_HOURS_BOOK: 'OFFICE_HOURS_BOOK',
  HOMEWORK_HELP: 'HOMEWORK_HELP',
  EXPLORE_DEEP_LINK: 'EXPLORE_DEEP_LINK',
  SAFETY_ESCALATE: 'SAFETY_ESCALATE',
  UNKNOWN_CLARIFY: 'UNKNOWN_CLARIFY'
};

export const ARTIFACT_TYPES = {
  MESSAGE_DRAFT: 'MESSAGE_DRAFT',
  BRIEF: 'BRIEF',
  SUMMARY: 'SUMMARY',
  DEEPLINK: 'DEEPLINK',
  OTHER: 'OTHER'
};

export const SAFETY_LEVELS = {
  NONE: 'NONE',
  SENSITIVE: 'SENSITIVE',
  URGENT: 'URGENT',
  BLOCKED: 'BLOCKED'
};
